services:
    app:
        build: .
        ports:
            - "8080:8080"
        networks:
            - claustroboard
    alloy:
        image: grafana/alloy:v1.10.2
        ports:
            - "12345:12345"
        env_file:
            - ./.env
        volumes:
            - ./config.alloy:/etc/alloy/config.alloy:ro
        networks:
            - claustroboard
networks:
    claustroboard:
        driver: bridge
